### ISSUE TITLE
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR

### ISSUE THREAD

**Issue by moiz-emx** [codez/delayed_cron_job#10]
I am trying to run a job every 2 minutes. Everytime, I run the job it runs fine the first time but at the end of the first run to enqueue the second run, it throws RecordNotUnique error. 

Does it create another row for second run in delayed_jobs table or does it update existing one (like a reset)?
If it is creating a new row, then it seems like it is using the job.id of running job.
Error is pasted below:

> ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "delayed_jobs_pkey"
> DETAIL:  Key (id)=(311) already exists.
> : INSERT INTO "delayed_jobs" ("handler", "run_at", "job_type", "job_step", "worker_id", "work_units_started", "work_units_completed", "work_units_failed", "status", "first_started_at", "last_started_at", "finished_at", "cron", "id", "created_at", "attempts", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17) RETURNING "id"
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in`block in exec_cache'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
>   from /var/lib/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in`exec_cache'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in`exec_query'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:192:in `exec_insert'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in`insert'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation.rb:64:in`insert'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/persistence.rb:524:in `_create_record'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/counter_cache.rb:139:in`_create_record'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/locking/optimistic.rb:75:in `_create_record'
>   from /var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/attribute_methods/dirty.rb:133:in`_create_record'
> ... 51 levels...
>   from /var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
>   from /var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in`block in initialize'
>   from /var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
>   from /var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in`block in add'
>   from /var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
>   from /var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in`execute'
>   from /var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
>   from /var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in`start'
>   from (irb):1
>   from /var/lib/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
>   from /var/lib/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in`start'
>   from /var/lib/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
>   from /var/lib/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in`run_command!'
>   from /var/lib/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
>   from bin/rails:4:in`require'
>   from bin/rails:4:in `<main>'

Any pointer/help is greatly appreciated.

Thanks!

**Comment by codez** [comment]
Yes, it does use the same id for new runs, so you can keep track of the job. Are you using a customized version of delayed job? There are a couple of non-standard columns in the table...

**Comment by moiz-emx** [comment]
We have customized to update those non-standard columns in the hooks.

If the job id is the same, then it should update but it is trying to insert. Any idea why it is doing that? Thank you for you help.

**Comment by codez** [comment]
It does so because delayed job already destroyed the record at this point.

**Comment by moiz-emx** [comment]
We have customized it to not delete completed jobs. Is there an easy way to fix this (update instead of insert)? Thanks codez for your help. I really appreciate it.

**Comment by codez** [comment]
DJ deletes the records after a successful run, therefore we have to insert it again, we cannot simply update. If you customize this behavior, I guess you have to customize delayed_cron_job, too.

**Comment by codez** [comment]
Closed because of inactivity.
