### ISSUE TITLE
Jobs not being rescheduled, and cron column is empty in DJ table

### ISSUE THREAD

**Issue by benevolentmadman** [codez/delayed_cron_job#12]
I'm using ruby 2.2.5 and rails 4.2.1 with the gem. Delayed job 4.1.2 and gem version 0.7.1.
When the job is created, it doesn't save the cron info in the database. The cron column was added to
the DJ table via the generator.

```
TestJob.set(cron: '*/5 * * * *').perform_later
Enqueued TestJob (Job ID: 2a916763-4677-4639-86bb-e6be265c58ad) to DelayedJob(default)
   (0.2ms)  BEGIN
  SQL (0.3ms)  INSERT INTO `delayed_jobs` (`queue`, `handler`, `run_at`, `created_at`, `updated_at`) VALUES ('default', '--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper\njob_data:\n  job_class: TestJob\n  job_id: 2a916763-4677-4639-86bb-e6be265c58ad\n  queue_name: default\n  arguments: []\n', '2017-01-10 19:09:44', '2017-01-10 19:09:44', '2017-01-10 19:09:44')
   (3.0ms)  COMMIT
 => #<TestJob:0x007fa4723a91c0 @arguments=[], @job_id="2a916763-4677-4639-86bb-e6be265c58ad", @queue_name="default", @cron="*/5 * * * *", @provider_job_id=25>
```

The insert into the delayed job table from the log does not include the cron column, and the run_at is the time of creation. The instance of my test job does have the cron info attached

After running the job queue, the job is not being rescheduled.

here's the source for my test job:

```
class TestJob < ActiveJob::Base
  def perform(*args)
    puts "Performing TestJob"
  end
end
```

**Comment by benevolentmadman** [comment]
Upon further investigation, I have discovered that when using the Delayed job syntax rather than the ActiveJob syntax, the cron column in the DJ table is filled in:
```
Delayed::Job.enqueue(TestJob.new, cron: '*/10 * * * *')
Enqueued TestJob (Job ID: 518c5569-eb63-434b-b3fb-de853f49c700) to DelayedJob(default)
   (0.2ms)  BEGIN
  SQL (0.3ms)  INSERT INTO `delayed_jobs` (`queue`, `handler`, `run_at`, `created_at`, `updated_at`) VALUES ('default', '--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper\njob_data:\n  job_class: TestJob\n  job_id: 518c5569-eb63-434b-b3fb-de853f49c700\n  queue_name: default\n  arguments: []\n', '2017-01-11 19:52:20', '2017-01-11 19:52:20', '2017-01-11 19:52:20')
   (2.2ms)  COMMIT
   (0.1ms)  BEGIN
  SQL (0.3ms)  INSERT INTO `delayed_jobs` (`cron`, `handler`, `queue`, `run_at`, `created_at`, `updated_at`) VALUES ('*/10 * * * *', '--- !ruby/object:TestJob\narguments: []\njob_id: 518c5569-eb63-434b-b3fb-de853f49c700\nqueue_name: default\n', 'default', '2017-01-11 20:00:00', '2017-01-11 19:52:20', '2017-01-11 19:52:20')
   (0.2ms)  COMMIT
```

**Comment by codez** [comment]
Please update your Rails version to at least 4.2.7.1 and check if the issue is still there.

**Comment by benevolentmadman** [comment]
The issue is resolved with rails 4.2.7.1, unfortunately that breaks our app for other reasons that are non-trivial to fix right now. 

Is there an older gem version that will work with 4.2.1? If not I'll fall back on the Delayed Job syntax, which does seem to work.

Thanks for the help.

**Comment by codez** [comment]
No, we only introduced ActiveJob Support around Rails 4.2.6. I guess you have to stick to the Delayed Job syntax for now.

**Comment by benevolentmadman** [comment]
OK, thanks for the help.
