### ISSUE TITLE
not auto-destroying failed jobs

### ISSUE THREAD

**Issue by kares** [codez/delayed_cron_job#13]
DJ's `Delayed::Worker.destroy_failed_jobs = false` setting won't have an effect on cron jobs.

seems as a bug: https://github.com/codez/delayed_cron_job/blob/master/lib/delayed_cron_job/plugin.rb#L20 could execute the same code as [DJ](https://github.com/collectiveidea/delayed_job/blob/v4.1.1/lib/delayed/worker.rb#L259) :
```ruby
 job.destroy_failed_jobs? ? job.destroy : job.fail!
```
... but maybe it messes with current assumption elsewhere while query-ing for (cron) jobs?

**Comment by codez** [comment]
Cron job instances behave differently from regular delayed jobs. They are never destroyed, not even after failures. In most cases, it makes sense to allow failures for individual executions and to keep the interval going.

If you wish to destroy a job on failure, do so inside your job logic. See the [tests](https://github.com/codez/delayed_cron_job/blob/master/spec/delayed_cron_job_spec.rb#L164) for more details.

**Comment by kares** [comment]
@codez thanks for the feedback, I understand but it seems to me like it could be made working ...
there would be an additional `where(:failed_at => nil)` while querying and the destruction logic would (optionally) keep them. would it be acceptable if put into code or do you rather not want to have such logic?

**Comment by codez** [comment]
I guess this would require some more adjustments to make all tests pass. 
Still not sure if it makes sense when the behavior for regular and cron jobs is always the same. I usually want to destroy failed regular jobs but keep cron jobs running, even if a single one fails. Could this still be realized?
