### ISSUE TITLE
Two Entries in Delayed Jobs Table

### ISSUE THREAD

**Issue by enhendrickson** [codez/delayed_cron_job#17]
`Delayed::Job.enqueue(MyRepeatedJob.new, cron: '15 */6 * * 1-5')`

For some reason this creates two records in the Delayed Jobs table: one for the Job and one for the JobWrapper

**Comment by codez** [comment]
If your Job inherits from `ActiveJob::Base`, schedule with `MyRepeatedJob.set(cron: '15 */6 * * 1-5').perform_later`, as described here: https://github.com/codez/delayed_cron_job#usage
