### ISSUE TITLE
Check for cron job already enqueued

### ISSUE THREAD

**Issue by ajays1991** [codez/delayed_cron_job#18]
Hey, I have implemented delayed_cron_job in my rails app. We use elasticbeanstalk for environment management. I have implemented rake task to enqueue all our crons.

I was looking for a way to check if the cron job is already enqueued in the delayed_jobs table in database. As we redeploy the code the rake task will run every time to enqueue all cron jobs so the cron jobs will be duplicated.
So i need to put a check in the rake to check if the cron is already enqueued.

Thanks

**Comment by codez** [comment]
It depends if you are using ActiveJob or not. Basically, if you have one job class per cron job, you can just check if a handler matching your job class exists in the database. 

```
Delayed::Job.where('handler LIKE ?', "%job_class: #{MyJob.name}%").exists?
```

**Comment by codez** [comment]
Added description in Readme: https://github.com/codez/delayed_cron_job#scheduling

**Comment by ajays1991** [comment]
Thanks
