### ISSUE TITLE
documentation not entirely clear about how to implement recurring jobs

### ISSUE THREAD

**Issue by fwolfst** [codez/delayed_cron_job#19]
First off: thanks for your efforts.

I use Rails6 and delayed_job and want a job that runs daily at 7:00 am.
I use dokku do deploy and do not want to set up an trigger to enque the jobs.

I will figure out how `delayed_cron_jobs` can help me. I have to say from the `README` itself I cannot figure that out. If you accept PRs, I will draft a documentation PR. I sense that it might also be desirable to have a generator for creating `app/jobs/cron_job.rb` and a `def cron_expression=value` in it, but I will have to dig deeper to understand if that would be really helpful.

Please give me a feedback before I write up some documentation draft.

**Comment by codez** [comment]
Sure, feel free to improve whatever you find. Please separate the single issues into single pull requests.

**Comment by fwolfst** [comment]
okay, I'll have a look. I think, what was missing for me was an example of a `CronJob` subclass (with `self.cron_expression = '* * * * *'`.

I would put my explanations in `doc/rails6_example.md` for now, which is `.gitignored` at the moment. It might end up in the README but I would leave that up to you. Do you object `doc/*md` ?

**Comment by codez** [comment]
I prefer to have stuff simple. Just put it in the README. Otherwise, if you think of an extended example for a special use case, the wiki might be another option.

**Comment by fwolfst** [comment]
Ya, I dont like documentation very much outside of the repo (
https://github.com/fwolfst/your-repository/issues/2) or the gem (
https://github.com/fwolfst/your-repository/issues/1). Will try to make it
concise so it fits the readme.
