### ISSUE TITLE
Implement generators for `CronJob` and helper classes

### ISSUE THREAD

**Issue by fwolfst** [codez/delayed_cron_job#23]
It would be user-friendly to have the examplary `CronJob` implementation and probably also the impementation to check for and schedule all `CronJob` subclasses available **in the gem** (might be difficult for non `Active*` implementations, do not know), or as generators along the lines `rails g delayed_cron_job:install`.

This probably boils down to only few lines of code in the Generator implementing `create_files` and using `copy_file` or `template`. Never done this, though.

(related to #22 )

**Comment by codez** [comment]
Users should be able to customize the `CronJob` class, so a generator is preferable. Pull requests are wellcome.

**Comment by fwolfst** [comment]
>  should be able to customize the `CronJob` class, so a generator is preferable

Oh yeah. Good point.

**Comment by codez** [comment]
> Unfortunately, no budget on my end.
Same here.

**Comment by codez** [comment]
Stale issue, closing.
