### ISSUE TITLE
Incompatible with delayed_job_active_record v1.4.5

### ISSUE THREAD

**Issue by f-mer** [codez/delayed_cron_job#27]
In version v1.4.5 of [`delayed_job_active_record`](https://github.com/collectiveidea/delayed_job_active_record/) the loading of `Delayed::Backend::ActiveRecord::Job` was [moved into a railtie which requires it now after initialization](https://github.com/collectiveidea/delayed_job_active_record/blob/master/lib/delayed/backend/active_record/railtie.rb#L7). This blows up in [`delayed_cron_job.rb:27`](https://github.com/codez/delayed_cron_job/blob/master/lib/delayed_cron_job.rb#L27) because  `require 'delayed_job_active_record'` does not load `Delayed::Backend::ActiveRecord::Job`. 

The reasoning behind this change is documented in https://github.com/collectiveidea/delayed_job_active_record/pull/172.

**Comment by codez** [comment]
Thank you for your fast notification of the issue. With those detailed debug hints, it was an easy way to fix this issue. Do you have time for a quick test on your side, based on #28?

**Comment by f-mer** [comment]
Hello @codez that was quick, thanks :smiley:  I just ran into this while upgrading an application to Rails 6.2. and thought it would be helpful to leaf a note. No pressure on my side.

For this to work the `after_initialize` callback registered by `delayed_job_active_record` must be triggered before the one registered by `delayed_cron_job` or? My wild guess is that the could a scenario where this would fail :thinking:

**Comment by nevesenin** [comment]
Works great. Thank you.

**Comment by codez** [comment]
By requiring `delayed_job_active_record` first in `delayed_cron_job.rb`, the callback should also be registered first. So everything should be in the correct order.

**Comment by codez** [comment]
A new version of the gem is released.
