### ISSUE TITLE
Rails 6.1 and Active Jobs doesn't reschedule

### ISSUE THREAD

**Issue by swobspace** [codez/delayed_cron_job#31]
I'm using Rails 6.1.4.1 with delayed_job_active_record and delayed_cron_job 0.7.4. Using the ActiveJob approach
starts only once, but no entries remains in the database.

```
MyJob.set(cron: '*/5 * * * *').perform_later
```

doesn't work. Using DelayedJob.enqueue as

```
Delayed::Job.enqueue(MyRepeatedJob.new, cron: '15 */6 * * 1-5')
```
works as expected. Any ideas?

**Comment by codez** [comment]
Does your job run successfully or is there any kind of failure? So far, I cannot reproduce your issue.

**Comment by swobspace** [comment]
The job run successfully, but only once. I get no remaining entry -> Delayed::Job.all = []

**Comment by codez** [comment]
Can you please run the delayed_cron_job test suite (`rake test`) with your setup? [This test](https://github.com/codez/delayed_cron_job/blob/ca257001bd56f9067912fd99296977cd301395d6/spec/active_job_spec.rb#L34) should actually cover your issue. If that works, please write a failing spec.

**Comment by swobspace** [comment]
I found the problem: some of my initializers like config/initializers/active_job.rb won't work any longer with Rails 6.x:

```
# config/initializers/active_job.rb
Rails.application.configure do
  unless Rails.env == 'test'
    config.active_job.queue_adapter = :delayed_job
    config.active_job.queue_name_prefix = "mirco_" + Rails.env.to_s
  end
end
```
If I move the snippet back to config/application.rb, ActiveJob backgrounding works as expected and scheduling too. If this snippet goes to an initializer, Rails.application.config shows delayed_job as queue_adapter, but perform_later does never put an job into the background.
