### ISSUE TITLE
Supporting the delayed gem

### ISSUE THREAD

**Issue by f-mer** [codez/delayed_cron_job#32]
The [`gem "delayed"`](https://github.com/Betterment/delayed) seems to be an active fork of [`delayed_job`](https://github.com/collectiveidea/delayed_job) and [`delayed_job_active_record`](https://github.com/collectiveidea/delayed_job_active_record/) which supports Rails 7.  Switching from `delayed_job` to `delayed` makes none of the tests of this gem fail. 

For making `delayed` work with this gem the line `spec.add_dependency "delayed_job", ">= 4.1"` has to be removed from `delayed_cron_jobb.gemspec`. Additionally CI tasks should be added to test with `delayed_job` and `delayed`.

Is there any interest in supporting `delayed`?

**Comment by codez** [comment]
I merged and released a new version 🎉

**Comment by f-mer** [comment]
Hi @codez, turns out there are some minor issues that prevented using this fabulous gem with delayed. I've updated the code to work with delayed [over here](https://github.com/f-mer/delayed_cron_job/tree/delayed-support). Any chance you are interested in a PR?

Otherwise I'm thinking about publishing a delayed specific gem.

Thanks for your efforts!

**Comment by codez** [comment]
Thank you, that looks good and is a step towards better maintainability. I would be interested in a PR.
