### ISSUE TITLE
Config file for scheduling cron jobs

### ISSUE THREAD

**Issue by dmitrypol** [codez/delayed_cron_job#4]
I love the functionality of this gem as it frees me from being depending on cron on specific linux server to kick off by DelayedJobs.  
Before I used whenever and it would automatically recreate that crontab on every deploy.  Now I have to manually put the jobs into DB via 
bundle exec rails r -e production "MyJobdelay(cron: '*/5 * * * *').perform"

It would be nice to have a simple config file where you would define these jobs and they would be recreated on every deploy.

**Comment by codez** [comment]
I think this depends on how you actually identify your jobs. Basically, this is nothing else than seed data for your database. So you can use the existing mechanism like `db/seed.rb` for that.
