### ISSUE TITLE
Jobs not being rescheduled after perform

### ISSUE THREAD

**Issue by glappen** [codez/delayed_cron_job#6]
Hello,

I am using your gem to implement recurring jobs, but my attempts to get a simple case going are failing.  I have defined a custom job class like this:

    class TestJob
      def perform
        puts "Performing TestJob!!!!"
      end
    end

And then I enqueue it with:
    
    j = Delayed::Job.enqueue(TestJob.new, cron: '* * * * *')

It runs once, and then is deleted.  No other job is inserted after.  Am I missing something obvious?

Thanks!

**Comment by codez** [comment]
delayed_job 4.1 changed the way plugins get loaded. I adjusted to that now. Could you please check if this issue still occurs in delayed_cron_job 0.6.0?

**Comment by glappen** [comment]
I just updated to 0.6.0 and re-tested.  It works great!  Thanks for the extremely quick fix on that!

**Comment by codez** [comment]
Great, thanks for the notice!
