### ISSUE TITLE
Can I run cron task every second?

### ISSUE THREAD

**Issue by sh8** [codez/delayed_cron_job#9]
like this:
```
TestJob.set(cron: '*/1 * * * * *').perfom_later
```

**Comment by codez** [comment]
Theoretically, you can (`*/1` is the same as `*`). You just have to configure delayed jobs to look for jobs every second or more (`Delayed::Worker.sleep_delay`). 

That said, I'm not sure how exact this will be eventually. Depends on your job. Go measure it :)

**Comment by sh8** [comment]
Thanks a lot :)

By the way, if I set cron like as follows,  I can run cron task every 5 seconds?
```
TestJob.set(cron: '*/5 * * * * *').perfom_later
```

**Comment by codez** [comment]
Yes.
